morango/models.py
morango/utils/uuids.py
requirements/base.txt
tests/testapp/facility_profile/models.py

We now calculate uuids based on the partition values of the model, as well as the source id (which will be unique fields on the model or a random uuid). 
NOTE:
Tests will break, but we will fix at a later time.

Change the way we calculate uuids.

---

morango/manager.py

This is how we are supposed to inherit so methods get copied on the queryset class correctly.

Correctly inherit from SyncableQuerySet.

---

morango/utils/register_models.py
requirements/base.txt

`Proxied_children` is an internal django field that was used but later removed. We still use the internal api for registering proxy models, but the methods are consistent across latest versions of django.

Stop using proxied_children in django internal api.

---

requirements/base.txt

It's dangerous down the road to have no upper bounds. Of course it's hard to tell the future, but the best bet is to trust the semantic versioning competence of the upstream :)
I'm leaving out requests, because their version schema was to hard to crack for me :)

Add upper bounds to requirements

---

Makefile

I used the same procedure from Kolibri, whereby `release` doesn't depend on `dist` -- it's nice because then you can run `dist`, check that everything is working (in some local `pip install dist/morango-x.y.whl`) and then run `make release`

Use twine for releasing

---

morango/models.py
tests/testapp/tests/test_uuid_utilities.py

Fix that actually sets previously created Instance IDs current flag to true.
Instance IDs that were created and then retrieved from swapping out wifi dongles did not reset the current flag to True. So the incorrect instance ID model would be set to true.

Explicitly set current flag to True after retrieval/creation.

---

.travis.yml
manage.py
requirements/test.txt
setup.cfg
tox.ini

Changes tox to use current Python environment and sets Travis to test with Python 2.7, 3.4, 3.5, 3.6

Expand test matrix w/ different django+cryptography releases

---

morango/utils/sync_utils.py
tests/testapp/tests/test_controller_methods.py

Resets deleted flag on the store records.
A model that was deleted/synced would set its store's deleted flag to `True`. If the model was created again (as long as it has the same `id`), upon serialization the deleted flag would not be set to `False`. This had the problem of syncing with another device, that the model would not be deserialized because its store record says its deleted.

Update store deleted flag if object is recreated after being deleted.

---

.travis.yml
morango/models.py
morango/utils/backends/base.py
morango/utils/backends/postgres.py
morango/utils/backends/sqlite.py
morango/utils/backends/utils.py
morango/utils/sync_utils.py
requirements/postgres.txt
tests/testapp/testapp/postgres_test.py
tests/testapp/tests/helpers.py
tests/testapp/tests/test_syncsession_methods.py
tox.ini

Since there were some sqlite queries that did not work for postgres, this PR aims to rectify that. Depending on the database backend used, we route to the correct db specific SQL queries.
**Note: This is temporary until we add a SQLAlchemy layer to replace the raw SQL queries**
https://github.com/ralphiee22/morango/blob/f6cfbc55d4c5c00a7de963c843d2e77750b66e9b/morango/utils/backends/postgres.py is probably of most interest, since that has the new postgres compatible SQL queries. Everything else is just a refactor to route to specific db backend.
SQL queries did not work on postgres, but now they do.

Db backend routing

---

morango/apps.py

We are removing db access during `apps.py` (app loading time).
As long as we always get the `InstanceIDModel` with `InstanceIDModel.get_or_create_current_instance()`, there should be no problem in getting the latest instance id. 
Also, we are moving the responsibility of loading morango cert fixtures to the calling application.

Remove db access at app loading time

---

morango/models.py
morango/util.py

Signals are executed when we are deserializing (saving) a store object into the app layer. This can have some unwanted side effects such as creating other models. We turn off signals whenever we deserialize an object.

Mute save signals before saving a model through deserialization

---

morango/api/serializers.py
morango/utils/sync_utils.py

We go from saving each buffer object individually, to bulk saving them. Now we should only be doing 2 queries for **_creating/saving_** the records sent to the buffer endpoint. 
Do tests still pass?

bulk create buffer objects as well

---

morango/constants/file.py

Current SQLITE_MAX_VARIABLE_NUMBER.cache is created in the same folder where kolibri is started. If the user does not have permissions on that folder, kolibri fails.
This is an important problem when running the kolibri daemon from the kolibri package, because it's executed this way:
`su kolibri -c "kolibri start"`
being `/` the execution folder.
This PR ensures this file is created in the user home dir.
The issue is easy to reproduce just doing:
```
cd /var
kolibri --foreground start
```
Closes: #67 
If the PR has documentation, link the file here (either .rst in your repo or if built on Read The Docs)

Add the needed path to the cache file

---

morango/constants/file.py
requirements/base.txt

Latest changes in file.py introduced a bug in Windows because it tries to use the `pwd` module , which is unix only. 
It's a simple check
Ensure a correct writable path is used

pwd is not available in Windows

---

morango/__init__.py
morango/apps.py
morango/constants/file.py
morango/util.py
morango/utils/backends/sqlite.py

There were several issues arising in Kolibri as a result of the pesky `SQLITE_MAX_VARIABLE_NUMBER.cache` file, so this PR switches to just using Django's `lru_cache` to memoize the result of the function, so we can call it as many times as we want. It's not so expensive to compute the first time (70ms for me), and only needs to be run once per process, so I think this should be fine.

Switch from file-based caching to Django's lru_cache for sqlite max vars

---

morango/__init__.py
morango/sync/operations.py
tests/testapp/testapp/postgres_test.py

As part of discussions around issues with read concurrency, we are enforcing implementing apps to have a separate db connection of serializable isolation level. This forces the operations to execute serially, as opposed to concurrently. 
Should address data leakage between concurrent transactions.

serialized isolation level decorator for postgres transactions

---

docs/dev/index.rst
morango/api/viewsets.py
morango/sync/operations.py
morango/sync/session.py
morango/sync/syncsession.py
morango/sync/utils.py
tests/testapp/tests/helpers.py
tests/testapp/tests/test_connection.py
tests/testapp/tests/test_syncsession_methods.py

Splits up the `SyncClient` class into a base class and two classes for each sync direction, `PullClient` and `PushClient`. This will enable us to better handling any database locking that should occur during the sync stages. I've left a small wrapper class in place for `SyncClient` such that this change should be backwards compatible for now.
This also fixes bandwidth tracking by attempting to track the response body size if there isn't a `Content-Length` header. It also now tracks the headers to get a better estimate of the entire request/response size.
Additionally, this fixes request exception handling in the `SessionWrapper`. Firstly, it was casting errors to strings which the errors being captured don't have a `__str__` method defined, so it now simply logs the error class name. …

Split up `SyncClient` and fix bandwidth tracking

---

morango/__init__.py
morango/api/viewsets.py
tests/testapp/tests/test_api.py

We were seeing this Exception on KDP, when `records_total` was `None`: `'>' not supported between instances of 'NoneType' and 'int'`.
https://sentry.io/organizations/learningequality/issues/1786330759/?project=1486197&query=is%3Aunresolved&sort=freq&statsPeriod=14d

Don't die on session deletion when transfersession.records_total is None

---

morango/__init__.py
morango/models/core.py
morango/models/utils.py
tests/testapp/tests/test_uuid_utilities.py

On KDP (or in Docker-based distributions more broadly), the detected MAC address is randomly generated, leading to regeneration of the instance_id more frequently than is desired (and in some cases, database lockups, in a multi-node setup). This PR allows the detected MAC value to be overridden with a fixed value, to increase the instance_id stability in these environments.

Allow MAC address to be overridden by envvar for instance_id calculation

---

morango/management/commands/cleanupsyncs.py
tests/testapp/tests/helpers.py
tests/testapp/tests/test_management_commands.py

If sync sessions are interrupted, or time out, they may not be closed out successfully, leaving possibly large amounts of data in the buffers. This management command can be called to close out and clean up after sync sessions that are older than a certain number of hours.

Add management command to close old sessions and clear out the buffers

---

morango/models/core.py
tests/testapp/tests/integration/test_syncsession.py
tests/testapp/tests/models/test_core.py

Ensures `last_activity_timestamp` on both `SyncSession` and `TransferSession` are updated when "activity" occurs. In this case, activity is registered when a `TransferSession` progresses through transfer stages.
Does `last_activity_timestamp` get updated as a sync progresses?
Fixes https://github.com/learningequality/morango/issues/119

Trigger update to `last_activity_timestamp`

---

CHANGELOG.md
morango/__init__.py
morango/api/viewsets.py
morango/sync/context.py
morango/sync/controller.py
morango/sync/operations.py
morango/sync/syncsession.py
morango/sync/utils.py
morango/utils.py
tests/testapp/tests/integration/test_syncsession.py
tests/testapp/tests/sync/test_context.py
tests/testapp/tests/sync/test_syncsession.py
tests/testapp/tests/test_api.py
tests/testapp/tests/test_utils.py

- Don't boolean compare against `get_filter()` as it always returns a `Filter` object
- Raise error in viewset cleanup if set on context for better insights
- Debug logging to track invocation and results of operations
- Set counters on `TransferSession` after serialization
- Fix capabilities header as it should be prefixed with `HTTP`
- Fix issues with flow of operations
From Kolibri, testing with `INTEGRATION_TEST=1 pytest -x kolibri/core/auth/test/test_morango_integration.py ` was helpful

Morango 0.6.1 fixes

---

CHANGELOG.md
morango/__init__.py
morango/api/viewsets.py
morango/sync/controller.py
morango/sync/syncsession.py
tests/testapp/tests/sync/test_controller.py
tests/testapp/tests/sync/test_syncsession.py

I forgot to circle back around to ensuring the sleeping interval between checks on an operation's status is optimal. The result was that we were sleeping a lot, too much, and it slowed down syncing quite a bit.
| Before | After |
| --- | ---
| ![Screenshot from 2021-07-26 16-14-01](https://user-images.githubusercontent.com/819838/127073605-b79e65c1-0cd3-4a48-89e4-c20470c15f0c.png) | ![Screenshot from 2021-07-26 16-44-51](https://user-images.githubusercontent.com/819838/127073657-91f3b6cd-8595-4605-a4cc-fddcd497f640.png) |
You probably can't tell from the tests that it will be faster.

Fix handling of sleep for `proceed_to_and_wait_for`

---

CHANGELOG.md
morango/__init__.py
morango/constants/settings.py
morango/sync/operations.py
morango/sync/syncsession.py
tests/testapp/tests/integration/test_syncsession.py
tests/testapp/tests/sync/test_syncsession.py
tests/testapp/tests/test_utils.py

- When data remains unchanged, Morango was repeatedly syncing the same data which should not happen
- The issue was hard to pinpoint but was centered around order of operations regarding how we handle the counters for client/server which get set on the `TransferSession` and used for queuing data
- Key points are:
- Always operate on local context before operating on network context
- Always exchange counters during serialization stage
- Only update local counters when the receiver
1. Run a push and pull sync on a brand new instance with a server that has data
2. Repeat the sync without any data changes and ensure nothing is pulled

Fix counter handling causing repeated syncs of same data

---

CHANGELOG.md
morango/__init__.py
morango/api/permissions.py
morango/api/viewsets.py
morango/models/certificates.py
morango/models/core.py
morango/models/fields/uuids.py
morango/sync/controller.py
morango/sync/operations.py
morango/utils.py
tests/testapp/tests/models/test_core.py
tox.ini

- Python 4 android compiles `.py` files into `.pyo` by default which removes plain `assert` statements, the same behavior as `-O` flag
- Some other tweaks from Kolibri integration
- Are you able to sync Kolibri using `python -O`

Replace assert statements to avoid removal with python -O

---

CHANGELOG.md
morango/__init__.py
morango/errors.py
morango/sync/operations.py
tests/testapp/tests/sync/test_operations.py

- Fixes `Expression tree is too large (maximum depth 1000)` issue originating from client or server having many instance counters
- New test fails without change
Resolves https://github.com/learningequality/morango/issues/114

Chunk through fsics when queuing into the buffer

---

.buildkite/build.sh
.buildkite/pipeline.yml
CHANGELOG.md
morango/management/commands/cleanupsyncs.py
tests/testapp/tests/test_management_commands.py

- Adds `ids` argument to cleanup management command so we can initiate targeted cleanup of incomplete SoUD syncs
- Migrates buildkite to pipeline.yml (resolves: https://buildkite.com/learningequality/morango/builds/154#d38eb321-f1f9-4d70-b93a-34efb48d0fb3)
- Run management command with `--ids` arg

Add new ids argument to cleanupsyncs command
